variable "project_name" {}
variable "frontend-lb_security_group_id" {}
variable "Prod-NAT-ALB-Sbn_az1_id" {}
variable "Prod-NAT-ALB-Sbn_az2_id" {}
variable "backend-alb_security_group_id" {}
variable "Prod-webserver-Sbn_az1_id" {}
variable "Prod-webserver-Sbn_az2_id" {}
variable "prod-vpc_id" {}
variable "certificate_arn" {}