variable "Prod-NAT-ALB-Sbn_az1_id" {}
variable "internet_gateway" {}
variable "Prod-NAT-ALB-Sbn_az2_id" {}
variable "prod-vpc_id" {}
variable "Prod-webserver-Sbn_az1_id" {}
variable "Prod-webserver-Sbn_az2_id" {}
variable "Prod-Appserver-Sbn_az1_id" {}
variable "Prod-Appserver-Sbn_az2_id" {}
variable "Prod-databbase-Sbn_az1_id" {}
variable "Prod-databbase-Sbn_az2_id" {}